#!/bin/bash

# Parametrelerin tanımlanması
resourceGroupName="myResourceGroup"
location="EastUS"
storageAccountName="mystorageaccount$(date +%s)"  # Benzersiz bir ad için tarih ekleyerek oluşturulur
sku="Standard_LRS"  # Depolama SKU'su
kind="StorageV2"  # Depolama türü (Storage, StorageV2, BlobStorage)

# Resource Group oluşturulması
az group create --name $resourceGroupName --location $location

# Storage Account oluşturulması
az storage account create \
  --name $storageAccountName \
  --resource-group $resourceGroupName \
  --location $location \
  --sku $sku \
  --kind $kind

echo "Azure Storage Account başarıyla oluşturuldu: $storageAccountName"
